name: Build Treep for all platforms

on:
  push:
    branches: [ main ]
    paths: [ game/** ]
  pull_request:
    branches: [ main ]
    paths: [ game/** ]
  workflow_dispatch:

jobs:
  build:
    name: Build Treep
    strategy:
      matrix:
        target:
          - StandaloneLinux64
          # - StandaloneWindows64
          # - StandaloneOSX

          # - LinuxHeadlessSimulation # not available?
          # - WebGL # takes a very long time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: game/Library
          key: Library-${{ hashFiles('game/Assets/**', 'game/Packages/**', 'game/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: game
          targetPlatform: ${{ matrix.target }}

      # - uses: actions/upload-artifact@v4
      #   # lessen the number of artefacts that are uploaded
      #   if: |
      #     (github.event_name == 'workflow_dispatch') ||
      #     (github.event_name == 'push' && matrix.target == 'StandaloneLinux64') ||
      #     (github.event_name == 'pull_request' && matrix.target == 'StandaloneLinux64')
      #   with:
      #     name: ${{ matrix.target }} Build
      #     path: build
